"use client";
import { useState } from "react";
import Swal from "sweetalert2";
import { toast } from "react-toastify";
import { createAllergie,createAntecedent,createConstante,deleteAllergie,deleteAntecedent } from "@/app/actions/patients";
export default function PatientRelations({patient}:{patient:any}){const [tab,setTab]=useState("allergies");const [loading,setLoading]=useState(false);const [a,setA]=useState<any>({});const [ant,setAnt]=useState<any>({});const [c,setC]=useState<any>({});
 const save=async(fn:any,data:any)=>{setLoading(true);const r=await fn({...data,patientId:patient.id});setLoading(false);r.success?toast.success(r.message):toast.error(r.message);if(r.success)location.reload()};
 const del=async(kind:string,id:number)=>{const x=await Swal.fire({title:"Supprimer ?",icon:"warning",showCancelButton:true,confirmButtonText:"Oui",cancelButtonText:"Annuler"});if(!x.isConfirmed)return;const r=kind==="a"?await deleteAllergie(id,patient.id):await deleteAntecedent(id,patient.id);r.success?toast.success(r.message):toast.error(r.message);if(r.success)location.reload()};
 const input=(obj:any,set:any,k:string,label:string)=><input className="input input-bordered" placeholder={label} value={obj[k]??""} onChange={e=>set((x:any)=>({...x,[k]:e.target.value}))}/>;
 return <div className="mt-6 rounded-2xl border border-base-300 bg-base-100 shadow-sm"><div className="tabs tabs-boxed m-3">{[["allergies","Allergies"],["antecedents","Antécédents"],["constantes","Constantes"],["medical","Dossier médical"]].map(([k,l])=><button key={k} className={`tab ${tab===k?"tab-active":""}`} onClick={()=>setTab(k)}>{l}</button>)}</div><div className="p-5">
 {tab==="allergies"&&<><div className="grid gap-2 md:grid-cols-4">{input(a,setA,"allergene","Allergène *")}{input(a,setA,"reaction","Réaction")}{input(a,setA,"gravite","Gravité")}{input(a,setA,"description","Description")}<button disabled={loading} className="btn btn-primary md:col-span-4" onClick={()=>save(createAllergie,a)}>Ajouter l'allergie</button></div><div className="divider"/><div className="overflow-x-auto"><table className="table"><thead><tr><th>Allergène</th><th>Réaction</th><th>Gravité</th><th>Description</th><th/></tr></thead><tbody>{patient.allergies.map((x:any)=><tr key={x.id}><td>{x.allergene}</td><td>{x.reaction||"—"}</td><td>{x.gravite||"—"}</td><td>{x.description||"—"}</td><td><button className="btn btn-xs btn-error btn-outline" onClick={()=>del("a",x.id)}>Supprimer</button></td></tr>)}</tbody></table></div></>}
 {tab==="antecedents"&&<><div className="grid gap-2 md:grid-cols-3">{input(ant,setAnt,"type","Type *")}{input(ant,setAnt,"libelle","Libellé *")}{input(ant,setAnt,"description","Description")}<button disabled={loading} className="btn btn-primary md:col-span-3" onClick={()=>save(createAntecedent,ant)}>Ajouter l'antécédent</button></div><div className="divider"/><table className="table"><thead><tr><th>Type</th><th>Libellé</th><th>Description</th><th/></tr></thead><tbody>{patient.antecedents.map((x:any)=><tr key={x.id}><td>{x.type}</td><td>{x.libelle}</td><td>{x.description||"—"}</td><td><button className="btn btn-xs btn-error btn-outline" onClick={()=>del("ant",x.id)}>Supprimer</button></td></tr>)}</tbody></table></>}
 {tab==="constantes"&&<><div className="grid gap-2 md:grid-cols-5">{["temperature","tensionSystolique","tensionDiastolique","pouls","saturation","poids","taille","frequenceRespiratoire","glycemie"].map(k=>input(c,setC,k,k))}<button disabled={loading} className="btn btn-primary md:col-span-5" onClick={()=>save(createConstante,c)}>Enregistrer les constantes</button></div><div className="divider"/><div className="overflow-x-auto"><table className="table"><thead><tr><th>Date</th><th>Temp.</th><th>TA</th><th>Pouls</th><th>SpO₂</th><th>Poids</th><th>Glycémie</th></tr></thead><tbody>{patient.constantes.map((x:any)=><tr key={x.id}><td>{new Date(x.dateMesure).toLocaleString("fr-FR")}</td><td>{x.temperature??"—"}</td><td>{x.tensionSystolique&&x.tensionDiastolique?`${x.tensionSystolique}/${x.tensionDiastolique}`:"—"}</td><td>{x.pouls??"—"}</td><td>{x.saturation??"—"}</td><td>{x.poids??"—"}</td><td>{x.glycemie??"—"}</td></tr>)}</tbody></table></div></>}
 {tab==="medical"&&<div className="grid gap-4 md:grid-cols-2"><Info title="Rendez-vous" items={patient.rendezVous} render={(x:any)=>`${new Date(x.dateHeure).toLocaleString("fr-FR")} — ${x.motif||"Sans motif"}`}/><Info title="Admissions" items={patient.admissions} render={(x:any)=>`${x.numero||`Admission #${x.id}`} — ${x.type} — ${x.statut}`}/><Info title="Consultations" items={patient.consultations} render={(x:any)=>`${new Date(x.dateConsultation).toLocaleDateString("fr-FR")} — ${x.diagnostic||x.motif||"Consultation"}`}/><Info title="Hospitalisations" items={patient.hospitalisations} render={(x:any)=>`${x.numero} — ${x.statut} — ${x.lit?`Lit ${x.lit.numero}`:"Sans lit"}`}/><Info title="Factures" items={patient.factures} render={(x:any)=>`${x.numero} — ${x.montantTotal} ${x.devise} — ${x.statut}`}/><Info title="Paiements" items={patient.paiements} render={(x:any)=>`${x.reference} — ${x.montant} ${x.devise} — ${x.modePaiement}`}/></div>}
 </div></div>}
function Info({title,items,render}:{title:string,items:any[],render:(x:any)=>string}){return <div className="rounded-xl border border-base-300 p-4"><h3 className="font-bold mb-2">{title} <span className="badge badge-sm">{items?.length??0}</span></h3>{items?.length?<ul className="space-y-2 text-sm">{items.map((x:any)=><li key={x.id} className="rounded-lg bg-base-200 p-2">{render(x)}</li>)}</ul>:<p className="text-sm opacity-60">Aucune donnée.</p>}</div>}
