"use client";
import { useEffect, useMemo, useState } from "react";
import { createProforma, getPatientConsultations, getPatientsFinance, getPrestationsFacturables } from "@/app/actions/finance";
import { useRouter } from "next/navigation";

export default function ProformaForm(){
 const router=useRouter(); const [patients,setPatients]=useState<any[]>([]); const [consultations,setConsultations]=useState<any[]>([]); const [rows,setRows]=useState<any[]>([]); const [patientId,setPatientId]=useState(""); const [consultationId,setConsultationId]=useState(""); const [devise,setDevise]=useState("USD"); const [typeReduction,setTypeReduction]=useState<"POURCENTAGE"|"MONTANT"|null>(null); const [reduction,setReduction]=useState("0"); const [loading,setLoading]=useState(false); const [saving,setSaving]=useState(false);
 useEffect(()=>{ getPatientsFinance().then(setPatients); },[]);
 useEffect(()=>{ if(!patientId){setConsultations([]);setRows([]);return;} getPatientConsultations(Number(patientId)).then(setConsultations); },[patientId]);
 useEffect(()=>{ if(!patientId||!consultationId){setRows([]);return;} setLoading(true); getPrestationsFacturables(Number(patientId),Number(consultationId)).then(setRows).finally(()=>setLoading(false)); },[patientId,consultationId]);
 const selected=rows.filter((r)=>r.selected!==false); const brut=useMemo(()=>selected.reduce((s,r)=>s+(Number(r.quantite)||0)*(Number(r.prixUnitaire)||0),0),[selected]); const red=typeReduction==="POURCENTAGE"?brut*(Number(reduction)||0)/100:Number(reduction)||0; const total=Math.max(0,brut-red);
 const toggle=(i:number)=>setRows(x=>x.map((r,j)=>j===i?{...r,selected:r.selected===false}:r));
 async function submit(){setSaving(true); const r=await createProforma({patientId:Number(patientId),consultationId:Number(consultationId),devise,typeReduction,reduction:Number(reduction),lignes:selected}); setSaving(false); if(r.success) router.push(`/facturation/proformas/${(r.data as any).id}`); else alert(r.message);}
 return <div className="mx-auto max-w-6xl p-6 space-y-5"><div><h1 className="text-3xl font-bold">Nouveau proforma</h1><p className="opacity-60">Sélectionne une consultation puis les prestations réalisées non encore facturées.</p></div>
 <div className="card border bg-base-100"><div className="card-body space-y-5"><div className="grid md:grid-cols-3 gap-4"><label className="form-control md:col-span-2"><span className="label-text font-medium">Patient *</span><select className="select select-bordered" value={patientId} onChange={e=>setPatientId(e.target.value)}><option value="">Sélectionner</option>{patients.map(p=><option key={p.id} value={p.id}>{p.numeroDossier} — {p.nom} {p.postNom||""} {p.prenom||""}</option>)}</select></label><label className="form-control"><span className="label-text font-medium">Devise</span><select className="select select-bordered" value={devise} onChange={e=>setDevise(e.target.value)}><option>USD</option><option>CDF</option></select></label></div>
 <label className="form-control"><span className="label-text font-medium">Consultation *</span><select className="select select-bordered" value={consultationId} onChange={e=>setConsultationId(e.target.value)} disabled={!patientId}><option value="">Sélectionner la consultation</option>{consultations.map(c=><option key={c.idConsultation} value={c.idConsultation}>CONS-{c.idConsultation} — {new Date(c.dateConsultation).toLocaleDateString("fr-FR")} — {c.service?.nom||"Service"} — Dr {c.medecin?.nom||""}</option>)}</select></label>
 <div className="divider">Prestations</div>{loading?<span>Recherche des prestations…</span>:rows.length===0?<p className="opacity-60">Aucune prestation candidate trouvée.</p>:<div className="overflow-x-auto"><table className="table"><thead><tr><th></th><th>Origine</th><th>Désignation</th><th>Référence</th><th>Qté</th><th>Total</th></tr></thead><tbody>{rows.map((r,i)=><tr key={`${r.reference}-${i}`} className={r.selected===false?"opacity-40":undefined}><td><input type="checkbox" className="checkbox" checked={r.selected!==false} onChange={()=>toggle(i)}/></td><td><span className="badge badge-outline">{r.typeOrigine}</span></td><td>{r.designation}</td><td>{r.reference}</td><td>{r.quantite}</td><td>{(r.montant||0).toFixed(2)} {devise}</td></tr>)}</tbody></table></div>}
 <div className="grid md:grid-cols-3 gap-4"><label className="form-control"><span className="label-text">Réduction</span><select className="select select-bordered" value={typeReduction||"AUCUNE"} onChange={e=>setTypeReduction(e.target.value==="AUCUNE"?null:e.target.value as any)}><option value="AUCUNE">Aucune</option><option value="POURCENTAGE">Pourcentage (%)</option><option value="MONTANT">Montant fixe</option></select></label><label className="form-control"><span className="label-text">Valeur</span><input className="input input-bordered" type="number" min="0" value={reduction} onChange={e=>setReduction(e.target.value)} disabled={!typeReduction}/></label><div className="rounded-box border p-4"><div className="text-sm opacity-60">Net à payer</div><div className="text-2xl font-bold">{total.toFixed(2)} {devise}</div></div></div>
 <div className="flex justify-end gap-2"><button className="btn btn-ghost" onClick={()=>router.back()}>Annuler</button><button className="btn btn-primary" disabled={saving||!patientId||!consultationId||selected.length===0} onClick={submit}>{saving?"Création…":"Créer le proforma"}</button></div>
 </div></div></div>;
}
