"use client";
import { useState } from "react";
import { toast } from "react-toastify";
import { createHospitalisation, updateHospitalisation } from "@/app/actions/hospitalisations";
export default function HospitalisationForm({ mode = "create", initial, admissions = [], services = [], medecins = [], lits = [] }: { mode?: "create" | "edit"; initial?: any; admissions?: any[]; services?: any[]; medecins?: any[]; lits?: any[] }) {
  const [loading, setLoading] = useState(false); const [form, setForm] = useState({ admissionId: initial?.admissionId ?? admissions[0]?.id ?? "", serviceId: initial?.serviceId ?? "", medecinId: initial?.medecinId ?? "", litId: initial?.litId ?? "", motif: initial?.motif ?? "", diagnostic: initial?.diagnostic ?? "", statut: initial?.statut ?? "EN_COURS" }); const set = (k: string, v: any) => setForm(f => ({ ...f, [k]: v }));
  async function submit(e: any) { e.preventDefault(); setLoading(true); try { const r = mode === "create" ? await createHospitalisation({ admissionId: Number(form.admissionId), serviceId: form.serviceId ? Number(form.serviceId) : null, medecinId: form.medecinId ? Number(form.medecinId) : null, litId: form.litId ? Number(form.litId) : null, motif: form.motif, diagnostic: form.diagnostic }) : await updateHospitalisation(initial.id, { serviceId: form.serviceId ? Number(form.serviceId) : null, medecinId: form.medecinId ? Number(form.medecinId) : null, litId: form.litId ? Number(form.litId) : null, motif: form.motif, diagnostic: form.diagnostic, statut: form.statut }); if (r.success) { toast.success(r.message); setTimeout(() => { location.href = "/hospitalisation/hospitalisations"; }, 700); } else toast.error(r.message); } catch { toast.error("Une erreur est survenue."); } finally { setLoading(false); } }
  return <form onSubmit={submit} className="space-y-5 rounded-2xl border border-base-300 bg-base-100 p-6 shadow-sm"><h2 className="text-xl font-bold">{mode === "create" ? "Nouvelle hospitalisation" : "Modifier l'hospitalisation"}</h2>{mode === "create" ? <label className="form-control"><span className="label-text font-semibold">Admission</span><select className="select select-bordered" value={form.admissionId} onChange={e => set("admissionId", e.target.value)} required><option value="">Sélectionner</option>{admissions.map(a => <option key={a.id} value={a.id}>{a.numero} — {[a.patient?.nom, a.patient?.postNom, a.patient?.prenom].filter(Boolean).join(" ")}</option>)}</select></label> : <div className="alert alert-info">{initial.numero} — {[initial.patient?.nom, initial.patient?.postNom, initial.patient?.prenom].filter(Boolean).join(" ")}</div>}<div className="grid gap-4 md:grid-cols-3"><label className="form-control"><span className="label-text font-semibold">Service</span><select className="select select-bordered" value={form.serviceId} onChange={e => set("serviceId", e.target.value)}><option value="">Aucun</option>{services.map(s => <option key={s.id} value={s.id}>{s.nom}</option>)}</select></label><label className="form-control"><span className="label-text font-semibold">Médecin</span><select className="select select-bordered" value={form.medecinId} onChange={e => set("medecinId", e.target.value)}><option value="">Aucun</option>{medecins.map(m => <option key={m.id} value={m.id}>Dr {[m.nom, m.postNom, m.prenom].filter(Boolean).join(" ")}</option>)}</select></label><label className="form-control"><span className="label-text font-semibold">Lit disponible</span><select className="select select-bordered" value={form.litId} onChange={e => set("litId", e.target.value)}><option value="">Aucun</option>{lits.map(l => <option key={l.id} value={l.id}>{l.chambre?.numero} / Lit {l.numero}</option>)}</select></label></div><label className="form-control"><span className="label-text font-semibold">Motif</span><textarea className="textarea textarea-bordered" value={form.motif} onChange={e => set("motif", e.target.value)} /></label><label className="form-control"><span className="label-text font-semibold">Diagnostic</span><textarea className="textarea textarea-bordered" value={form.diagnostic} onChange={e => set("diagnostic", e.target.value)} /></label><div className="flex justify-end gap-2"><a href="/hospitalisation/hospitalisations" className="btn btn-ghost">Annuler</a><button className="btn btn-primary" disabled={loading}>{loading ? "Enregistrement..." : "Enregistrer"}</button></div></form>;
}
