"use client";
import { useState } from "react";
import { toast } from "react-toastify";
import { createLit, updateLit } from "@/app/actions/lits";
export default function LitForm({ initial, chambres = [] }: { initial?: any; chambres?: any[] }) {
  const [f, setF] = useState({ numero: initial?.numero ?? "", chambreId: initial?.chambreId ?? chambres[0]?.id ?? "", statut: initial?.statut ?? "LIBRE" }); const [loading, setLoading] = useState(false); const s = (k: string, v: any) => setF(x => ({ ...x, [k]: v }));
  async function submit(e: any) { e.preventDefault(); setLoading(true); try { const r = initial ? await updateLit(initial.id, { numero: f.numero, chambreId: Number(f.chambreId), statut: f.statut }) : await createLit({ numero: f.numero, chambreId: Number(f.chambreId), statut: f.statut }); if (r.success) { toast.success(r.message); setTimeout(() => { location.href = "/hospitalisation/lits"; }, 700); } else toast.error(r.message); } catch { toast.error("Une erreur est survenue."); } finally { setLoading(false); } }
  return <form onSubmit={submit} className="space-y-4 rounded-2xl border border-base-300 bg-base-100 p-6 shadow-sm"><h2 className="text-xl font-bold">{initial ? "Modifier le lit" : "Nouveau lit"}</h2><input required className="input input-bordered w-full" placeholder="Numéro du lit" value={f.numero} onChange={e => s("numero", e.target.value)} /><select required className="select select-bordered w-full" value={f.chambreId} onChange={e => s("chambreId", e.target.value)}><option value="">Chambre</option>{chambres.map(c => <option key={c.id} value={c.id}>{c.numero}</option>)}</select><select className="select select-bordered w-full" value={f.statut} onChange={e => s("statut", e.target.value)}><option>LIBRE</option><option>MAINTENANCE</option>{initial?.statut === "OCCUPE" && <option>OCCUPE</option>}</select><div className="flex justify-end"><button className="btn btn-primary" disabled={loading}>{loading ? "..." : "Enregistrer"}</button></div></form>;
}
