"use client";
import { useState } from "react";
import { toast } from "react-toastify";
import { createSoin, updateSoin } from "@/app/actions/soins";
export default function SoinForm({ initial, hospitalisations = [] }: { initial?: any; hospitalisations?: any[] }) {
  const [f, setF] = useState({ hospitalisationId: initial?.hospitalisationId ?? hospitalisations[0]?.id ?? "", type: initial?.type ?? "", description: initial?.description ?? "", observation: initial?.observation ?? "", dateSoin: initial?.dateSoin ? new Date(initial.dateSoin).toISOString().slice(0, 16) : "" }); const [loading, setLoading] = useState(false); const s = (k: string, v: any) => setF(x => ({ ...x, [k]: v }));
  async function submit(e: any) { e.preventDefault(); setLoading(true); try { const r = initial ? await updateSoin(initial.id, { type: f.type, description: f.description, observation: f.observation, dateSoin: f.dateSoin }) : await createSoin({ hospitalisationId: Number(f.hospitalisationId), type: f.type, description: f.description, observation: f.observation, dateSoin: f.dateSoin }); if (r.success) { toast.success(r.message); setTimeout(() => { location.href = "/hospitalisation/soins"; }, 700); } else toast.error(r.message); } catch { toast.error("Une erreur est survenue."); } finally { setLoading(false); } }
  return <form onSubmit={submit} className="space-y-4 rounded-2xl border border-base-300 bg-base-100 p-6 shadow-sm"><h2 className="text-xl font-bold">{initial ? "Modifier le soin" : "Nouveau soin"}</h2>{!initial && <select required className="select select-bordered w-full" value={f.hospitalisationId} onChange={e => s("hospitalisationId", e.target.value)}><option value="">Hospitalisation</option>{hospitalisations.map(h => <option key={h.id} value={h.id}>{h.numero} — {[h.patient?.nom, h.patient?.prenom].filter(Boolean).join(" ")}</option>)}</select>}<input required className="input input-bordered w-full" placeholder="Type de soin" value={f.type} onChange={e => s("type", e.target.value)} /><input type="datetime-local" className="input input-bordered w-full" value={f.dateSoin} onChange={e => s("dateSoin", e.target.value)} /><textarea className="textarea textarea-bordered w-full" placeholder="Description" value={f.description} onChange={e => s("description", e.target.value)} /><textarea className="textarea textarea-bordered w-full" placeholder="Observation" value={f.observation} onChange={e => s("observation", e.target.value)} /><button className="btn btn-primary" disabled={loading}>{loading ? "..." : "Enregistrer"}</button></form>;
}
