"use client";
import { useState } from "react";
import { toast } from "react-toastify";
import { createTransfert } from "@/app/actions/transferts";
export default function TransfertForm({ hospitalisations = [], services = [], lits = [], hospitalisationId }: { hospitalisations?: any[]; services?: any[]; lits?: any[]; hospitalisationId?: number }) {
  const [f, setF] = useState({ hospitalisationId: hospitalisationId ?? hospitalisations[0]?.id ?? "", nouveauServiceId: "", nouveauLitId: "", motif: "" }); const [loading, setLoading] = useState(false); const s = (k: string, v: any) => setF(x => ({ ...x, [k]: v }));
  async function submit(e: any) { e.preventDefault(); setLoading(true); try { const r = await createTransfert({ hospitalisationId: Number(f.hospitalisationId), nouveauServiceId: f.nouveauServiceId ? Number(f.nouveauServiceId) : null, nouveauLitId: f.nouveauLitId ? Number(f.nouveauLitId) : null, motif: f.motif }); if (r.success) { toast.success(r.message); setTimeout(() => { location.href = "/hospitalisation/transferts"; }, 700); } else toast.error(r.message); } catch { toast.error("Une erreur est survenue."); } finally { setLoading(false); } }
  return <form onSubmit={submit} className="space-y-4 rounded-2xl border border-base-300 bg-base-100 p-6 shadow-sm"><h2 className="text-xl font-bold">Nouveau transfert</h2>{!hospitalisationId && <select required className="select select-bordered w-full" value={f.hospitalisationId} onChange={e => s("hospitalisationId", e.target.value)}><option value="">Hospitalisation</option>{hospitalisations.map(h => <option key={h.id} value={h.id}>{h.numero} — {[h.patient?.nom, h.patient?.prenom].filter(Boolean).join(" ")}</option>)}</select>}<select className="select select-bordered w-full" value={f.nouveauServiceId} onChange={e => s("nouveauServiceId", e.target.value)}><option value="">Nouveau service</option>{services.map(x => <option key={x.id} value={x.id}>{x.nom}</option>)}</select><select className="select select-bordered w-full" value={f.nouveauLitId} onChange={e => s("nouveauLitId", e.target.value)}><option value="">Nouveau lit</option>{lits.map(x => <option key={x.id} value={x.id}>{x.chambre?.numero} / Lit {x.numero}</option>)}</select><textarea className="textarea textarea-bordered w-full" placeholder="Motif du transfert" value={f.motif} onChange={e => s("motif", e.target.value)} /><button className="btn btn-primary" disabled={loading}>{loading ? "..." : "Effectuer le transfert"}</button></form>;
}
