"use server";
import { prisma } from "@/lib/prisma";
import { revalidatePath } from "next/cache";
type ActionResult<T = unknown> = { success: boolean; message: string; data?: T };
const PATH = "/hospitalisation/chambres";
export async function getChambres(): Promise<ActionResult> { try { const data = await prisma.chambre.findMany({ orderBy: { numero: "asc" }, include: { service: true, lits: true } }); return { success:true,message:"Chambres récupérées.",data }; } catch(e){ console.error(e); return {success:false,message:"Impossible de récupérer les chambres."}; } }
export async function getChambreById(id:number): Promise<ActionResult> { try { const data=await prisma.chambre.findUnique({where:{id},include:{service:true,lits:{orderBy:{numero:"asc"}}}}); if(!data)return{success:false,message:"Chambre introuvable."}; return{success:true,message:"Chambre récupérée.",data}; }catch(e){console.error(e);return{success:false,message:"Erreur lors de la récupération."};}}
export async function createChambre(input:{numero:string;type?:string|null;etage?:string|null;prixJournalier?:number;devise?:string;serviceId?:number|null}):Promise<ActionResult>{try{const numero=input.numero.trim();if(!numero)return{success:false,message:"Le numéro de chambre est obligatoire."};const exists=await prisma.chambre.findUnique({where:{numero}});if(exists)return{success:false,message:"Ce numéro de chambre existe déjà."};const data=await prisma.chambre.create({data:{numero,type:input.type?.trim()||null,etage:input.etage?.trim()||null,prixJournalier:Number(input.prixJournalier)||0,devise:input.devise?.trim()||"USD",serviceId:input.serviceId??null}});revalidatePath(PATH);return{success:true,message:"Chambre créée avec succès.",data};}catch(e){console.error(e);return{success:false,message:"Impossible de créer la chambre."};}}
export async function updateChambre(id:number,input:{numero:string;type?:string|null;etage?:string|null;prixJournalier?:number;devise?:string;serviceId?:number|null;actif?:boolean}):Promise<ActionResult>{try{const numero=input.numero.trim();const exists=await prisma.chambre.findFirst({where:{numero,id:{not:id}}});if(exists)return{success:false,message:"Ce numéro de chambre existe déjà."};const data=await prisma.chambre.update({where:{id},data:{numero,type:input.type?.trim()||null,etage:input.etage?.trim()||null,prixJournalier:Number(input.prixJournalier)||0,devise:input.devise?.trim()||"USD",serviceId:input.serviceId??null,actif:input.actif??true}});revalidatePath(PATH);revalidatePath(`/hospitalisation/chambres/${id}`);return{success:true,message:"Chambre modifiée.",data};}catch(e){console.error(e);return{success:false,message:"Impossible de modifier la chambre."};}}
export async function deleteChambre(id:number):Promise<ActionResult>{try{const chambre=await prisma.chambre.findUnique({where:{id},include:{lits:true}});if(!chambre)return{success:false,message:"Chambre introuvable."};if(chambre.lits.length>0)return{success:false,message:"Impossible de supprimer une chambre qui possède des lits. Supprimez ou déplacez d'abord les lits."};await prisma.chambre.delete({where:{id}});revalidatePath(PATH);return{success:true,message:"Chambre supprimée."};}catch(e){console.error(e);return{success:false,message:"Impossible de supprimer la chambre."};}}
