"use server";
import { prisma } from "@/lib/prisma";
import { revalidatePath } from "next/cache";
type ActionResult<T = unknown> = { success: boolean; message: string; data?: T };
const PATH="/hospitalisation/lits";
export async function getLits():Promise<ActionResult>{try{const data=await prisma.lit.findMany({orderBy:[{statut:"asc"},{numero:"asc"}],include:{chambre:{include:{service:true}},hospitalisations:{where:{statut:"EN_COURS"},include:{patient:true}}}});return{success:true,message:"Lits récupérés.",data};}catch(e){console.error(e);return{success:false,message:"Impossible de récupérer les lits."};}}
export async function getLitsDisponibles(chambreId?:number):Promise<ActionResult>{try{const data=await prisma.lit.findMany({where:{statut:"LIBRE",...(chambreId?{chambreId}:{})},orderBy:{numero:"asc"},include:{chambre:true}});return{success:true,message:"Lits disponibles récupérés.",data};}catch(e){console.error(e);return{success:false,message:"Impossible de récupérer les lits disponibles."};}}
export async function getLitById(id:number):Promise<ActionResult>{try{const data=await prisma.lit.findUnique({where:{id},include:{chambre:{include:{service:true}},hospitalisations:{orderBy:{dateEntree:"desc"},take:10,include:{patient:true}}}});if(!data)return{success:false,message:"Lit introuvable."};return{success:true,message:"Lit récupéré.",data};}catch(e){console.error(e);return{success:false,message:"Erreur lors de la récupération."};}}
export async function createLit(input:{numero:string;chambreId:number;statut?:string}):Promise<ActionResult>{try{const numero=input.numero.trim();if(!numero||!input.chambreId)return{success:false,message:"Numéro et chambre sont obligatoires."};const exists=await prisma.lit.findFirst({where:{numero,chambreId:input.chambreId}});if(exists)return{success:false,message:"Ce lit existe déjà dans cette chambre."};const data=await prisma.lit.create({data:{numero,chambreId:input.chambreId,statut:input.statut||"LIBRE"}});revalidatePath(PATH);revalidatePath("/hospitalisation/chambres");return{success:true,message:"Lit créé avec succès.",data};}catch(e){console.error(e);return{success:false,message:"Impossible de créer le lit."};}}
export async function updateLit(id:number,input:{numero:string;chambreId:number;statut?:string}):Promise<ActionResult>{try{const current=await prisma.lit.findUnique({where:{id}});if(!current)return{success:false,message:"Lit introuvable."};if(current.statut==="OCCUPE"&&(input.statut!=="OCCUPE"||input.chambreId!==current.chambreId||input.numero!==current.numero))return{success:false,message:"Un lit occupé ne peut pas être déplacé ou libéré manuellement."};const exists=await prisma.lit.findFirst({where:{numero:input.numero.trim(),chambreId:input.chambreId,id:{not:id}}});if(exists)return{success:false,message:"Ce lit existe déjà dans cette chambre."};const data=await prisma.lit.update({where:{id},data:{numero:input.numero.trim(),chambreId:input.chambreId,statut:input.statut||current.statut}});revalidatePath(PATH);return{success:true,message:"Lit modifié.",data};}catch(e){console.error(e);return{success:false,message:"Impossible de modifier le lit."};}}
export async function changerStatutLit(id:number,statut:string):Promise<ActionResult>{try{const lit=await prisma.lit.findUnique({where:{id},include:{hospitalisations:{where:{statut:"EN_COURS"}}}});if(!lit)return{success:false,message:"Lit introuvable."};if(statut==="LIBRE"&&lit.hospitalisations.length>0)return{success:false,message:"Le lit est encore affecté à une hospitalisation en cours."};const data=await prisma.lit.update({where:{id},data:{statut}});revalidatePath(PATH);return{success:true,message:"Statut du lit modifié.",data};}catch(e){console.error(e);return{success:false,message:"Impossible de modifier le statut du lit."};}}
export async function deleteLit(id:number):Promise<ActionResult>{try{const lit=await prisma.lit.findUnique({where:{id},include:{hospitalisations:true}});if(!lit)return{success:false,message:"Lit introuvable."};if(lit.hospitalisations.length>0)return{success:false,message:"Impossible de supprimer un lit ayant un historique d'hospitalisations."};await prisma.lit.delete({where:{id}});revalidatePath(PATH);return{success:true,message:"Lit supprimé."};}catch(e){console.error(e);return{success:false,message:"Impossible de supprimer le lit."};}}
