"use server";
import { prisma } from "@/lib/prisma";
import { revalidatePath } from "next/cache";
type ActionResult<T = unknown> = { success: boolean; message: string; data?: T };
const PATH="/hospitalisation/soins";
export async function getSoins():Promise<ActionResult>{try{const data=await prisma.soin.findMany({orderBy:{dateSoin:"desc"},include:{hospitalisation:{include:{patient:true,service:true}}}});return{success:true,message:"Soins récupérés.",data};}catch(e){console.error(e);return{success:false,message:"Impossible de récupérer les soins."};}}
export async function getSoinsByHospitalisation(hospitalisationId:number):Promise<ActionResult>{try{const data=await prisma.soin.findMany({where:{hospitalisationId},orderBy:{dateSoin:"desc"}});return{success:true,message:"Soins récupérés.",data};}catch(e){console.error(e);return{success:false,message:"Impossible de récupérer les soins."};}}
export async function getSoinById(id:number):Promise<ActionResult>{try{const data=await prisma.soin.findUnique({where:{id},include:{hospitalisation:{include:{patient:true}}}});if(!data)return{success:false,message:"Soin introuvable."};return{success:true,message:"Soin récupéré.",data};}catch(e){console.error(e);return{success:false,message:"Erreur lors de la récupération."};}}
export async function createSoin(input:{hospitalisationId:number;type:string;description?:string|null;observation?:string|null;dateSoin?:Date|string}):Promise<ActionResult>{try{if(!input.hospitalisationId||!input.type.trim())return{success:false,message:"Hospitalisation et type de soin sont obligatoires."};const hosp=await prisma.hospitalisation.findUnique({where:{id:input.hospitalisationId}});if(!hosp)return{success:false,message:"Hospitalisation introuvable."};if(hosp.statut!=="EN_COURS")return{success:false,message:"Le soin ne peut être ajouté qu'à une hospitalisation en cours."};const data=await prisma.soin.create({data:{hospitalisationId:input.hospitalisationId,type:input.type.trim(),description:input.description?.trim()||null,observation:input.observation?.trim()||null,dateSoin:input.dateSoin?new Date(input.dateSoin):new Date()}});revalidatePath(PATH);revalidatePath(`/hospitalisation/hospitalisations/${input.hospitalisationId}`);return{success:true,message:"Soin enregistré.",data};}catch(e){console.error(e);return{success:false,message:"Impossible d'enregistrer le soin."};}}
export async function updateSoin(id:number,input:{type:string;description?:string|null;observation?:string|null;dateSoin?:Date|string}):Promise<ActionResult>{try{const data=await prisma.soin.update({where:{id},data:{type:input.type.trim(),description:input.description?.trim()||null,observation:input.observation?.trim()||null,dateSoin:input.dateSoin?new Date(input.dateSoin):undefined}});revalidatePath(PATH);return{success:true,message:"Soin modifié.",data};}catch(e){console.error(e);return{success:false,message:"Impossible de modifier le soin."};}}
export async function deleteSoin(id:number):Promise<ActionResult>{try{await prisma.soin.delete({where:{id}});revalidatePath(PATH);return{success:true,message:"Soin supprimé."};}catch(e){console.error(e);return{success:false,message:"Impossible de supprimer le soin."};}}
