"use server";
import { prisma } from "@/lib/prisma";
import { revalidatePath } from "next/cache";
type ActionResult<T = unknown> = { success: boolean; message: string; data?: T };
const PATH="/hospitalisation/transferts";
export async function getTransferts():Promise<ActionResult>{try{const data=await prisma.transfert.findMany({orderBy:{dateTransfert:"desc"},include:{hospitalisation:{include:{patient:true,service:true,lit:{include:{chambre:true}}}}}});return{success:true,message:"Transferts récupérés.",data};}catch(e){console.error(e);return{success:false,message:"Impossible de récupérer les transferts."};}}
export async function getTransfertsByHospitalisation(hospitalisationId:number):Promise<ActionResult>{try{const data=await prisma.transfert.findMany({where:{hospitalisationId},orderBy:{dateTransfert:"desc"}});return{success:true,message:"Transferts récupérés.",data};}catch(e){console.error(e);return{success:false,message:"Impossible de récupérer les transferts."};}}
export async function createTransfert(input:{hospitalisationId:number;nouveauServiceId?:number|null;nouveauLitId?:number|null;motif?:string|null}):Promise<ActionResult>{try{const current=await prisma.hospitalisation.findUnique({where:{id:input.hospitalisationId}});if(!current)return{success:false,message:"Hospitalisation introuvable."};if(current.statut!=="EN_COURS")return{success:false,message:"Impossible de transférer une hospitalisation terminée."};if(!input.nouveauServiceId&&!input.nouveauLitId)return{success:false,message:"Choisissez au moins un nouveau service ou un nouveau lit."};if(input.nouveauLitId){const lit=await prisma.lit.findUnique({where:{id:input.nouveauLitId}});if(!lit)return{success:false,message:"Nouveau lit introuvable."};if(lit.statut!=="LIBRE"&&lit.id!==current.litId)return{success:false,message:"Le nouveau lit n'est pas libre."};}
const data=await prisma.$transaction(async(tx)=>{const transfert=await tx.transfert.create({data:{hospitalisationId:input.hospitalisationId,ancienServiceId:current.serviceId,nouveauServiceId:input.nouveauServiceId??current.serviceId,ancienLitId:current.litId,nouveauLitId:input.nouveauLitId??current.litId,motif:input.motif?.trim()||null}});if(current.litId&&current.litId!==input.nouveauLitId)await tx.lit.update({where:{id:current.litId},data:{statut:"LIBRE"}});if(input.nouveauLitId&&current.litId!==input.nouveauLitId)await tx.lit.update({where:{id:input.nouveauLitId},data:{statut:"OCCUPE"}});await tx.hospitalisation.update({where:{id:current.id},data:{serviceId:input.nouveauServiceId??current.serviceId,litId:input.nouveauLitId??current.litId}});return transfert;});revalidatePath(PATH);revalidatePath(`/hospitalisation/hospitalisations/${input.hospitalisationId}`);revalidatePath("/hospitalisation/lits");return{success:true,message:"Transfert effectué avec succès.",data};}catch(e){console.error(e);return{success:false,message:"Impossible d'effectuer le transfert."};}}
export async function deleteTransfert(id:number):Promise<ActionResult>{try{await prisma.transfert.delete({where:{id}});revalidatePath(PATH);return{success:true,message:"Transfert supprimé."};}catch(e){console.error(e);return{success:false,message:"Impossible de supprimer le transfert."};}}
